version: 2

jobs:
    test:
        docker:
            - image: cimg/python:3.11
        steps:
            - checkout

            - type: cache-restore
              keys:
                  - pip-{{ .Branch }}-
                  - pip-main-

            - run: pip install flit
            - run: flit install --deps production --extras testing

            - type: cache-save
              key: pip-{{ .Branch }}-{{ epoch }}
              paths:
                  - '~/.cache/pip'

            - run: python testmanage.py test

    nightly-wagtail-test:
        docker:
            - image: cimg/python:3.11
        steps:
            - checkout
            - run: git clone git@github.com:wagtail/wagtail.git

            - run: pip install flit
            - run: flit install --deps production --extras testing
            - run: |
                  pip install \
                  git+https://github.com/wagtail-nest/wagtail-modeladmin.git@main#egg=wagtail-modeladmin \
                  ./wagtail

            - run: python testmanage.py test

            - run:
                  when: on_fail
                  command: python ./.circleci/report_nightly_build_failure.py

workflows:
    version: 2
    test:
        jobs:
            - test

    nightly:
        jobs:
            - nightly-wagtail-test
        triggers:
            - schedule:
                  cron: '0 0 * * *'
                  filters:
                      branches:
                          only:
                              - main
